version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dashboard-server
    environment:
      PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - .:/srv

